-- File: toplevel.vhd
-- Generated by MyHDL 0.11.42
-- Date: Fri Sep  6 17:40:54 2024


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_01142.all;

entity toplevel is
    port (
        LEDR: in unsigned(9 downto 0);
        SW: in unsigned(9 downto 0);
        KEY: in unsigned(3 downto 0);
        HEX0: out unsigned(6 downto 0);
        HEX1: in unsigned(6 downto 0);
        HEX2: in unsigned(6 downto 0);
        HEX3: in unsigned(6 downto 0);
        HEX4: in unsigned(6 downto 0);
        HEX5: in unsigned(6 downto 0);
        CLOCK_50: in std_logic;
        RESET_N: in std_logic
    );
end entity toplevel;


architecture MyHDL of toplevel is




begin




TOPLEVEL_SW2HEX0_COMB: process (SW) is
begin
    if (SW(4-1 downto 0) = 0) then
        HEX0 <= unsigned'("1000000");
    elsif (SW(4-1 downto 0) = 1) then
        HEX0 <= unsigned'("1111001");
    elsif (SW(4-1 downto 0) = 2) then
        HEX0 <= unsigned'("0100100");
    elsif (SW(4-1 downto 0) = 3) then
        HEX0 <= unsigned'("0110000");
    elsif (SW(4-1 downto 0) = 4) then
        HEX0 <= unsigned'("0011001");
    elsif (SW(4-1 downto 0) = 5) then
        HEX0 <= unsigned'("0010010");
    elsif (SW(4-1 downto 0) = 6) then
        HEX0 <= unsigned'("0000010");
    elsif (SW(4-1 downto 0) = 7) then
        HEX0 <= unsigned'("1011000");
    elsif (SW(4-1 downto 0) = 8) then
        HEX0 <= unsigned'("0000000");
    elsif (SW(4-1 downto 0) = 9) then
        HEX0 <= unsigned'("0010000");
    elsif (SW(4-1 downto 0) = 10) then
        HEX0 <= unsigned'("0001000");
    elsif (SW(4-1 downto 0) = 11) then
        HEX0 <= unsigned'("0000011");
    elsif (SW(4-1 downto 0) = 12) then
        HEX0 <= unsigned'("0100111");
    elsif (SW(4-1 downto 0) = 13) then
        HEX0 <= unsigned'("0100001");
    elsif (SW(4-1 downto 0) = 14) then
        HEX0 <= unsigned'("0000110");
    else
        HEX0 <= unsigned'("0001110");
    end if;
end process TOPLEVEL_SW2HEX0_COMB;

end architecture MyHDL;
